nas:
  zuulClientRedirectUrl: http://192.168.99.100:7070/login

spring:
  application:
    name: auth

server:
  port: 8080
  context-path: /auth

logging:
  level:
    org.springframework.security: DEBUG