nas:
  zuulClientRedirectUrl: "http://192.168.99.100:7070/zuul/login"

spring:
  application:
    name: auth

server:
  port: 8080
  context-path: /uaa

logging:
  level:
    org.springframework.security: DEBUG