---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: frekele/java
    tag: jdk8

inputs:
  - name: CodeForBlog

run:
  #path: ls
  #args: ['-la', 'CodeForBlog/HelloDockerGradle']
  path: CodeForBlog/HelloDockerGradle/gradlew
  args: ['--version']
