resources:
  - name: CodeForBlog
    type: git
    source:
      uri: https://github.com/eshepelyuk/CodeForBlog.git
      branch: master

jobs:
  - name: HellDockerGradle
    plan:
      - get: CodeForBlog 
      - task: build
        file: CodeForBlog/HelloDockerGradle/build.yml 
