server:
  port: 7070
  context-path: /zuul

spring:
  application:
    name: zuul

zuul:
  routes:
    qwerty:
      path: /qwerty/**
      url: http://resource:9090
#    uaa:
#      path: /uaa/**
#      url: http://localhost:8080
#      stripPrefix: false

security:
  oauth2:
    resource:
      token-info-uri: http://none.no
      jwt:
        key-value: 123
    client:
      client-id: zuul
      client-secret: zuul123
      access-token-uri: http://192.168.99.100:8080/uaa/oauth/token
      user-authorization-uri: http://192.168.99.100:8080/uaa/oauth/authorize

logging:
  level:
    org.springframework.security: DEBUG