nas:
  resourceHost: http://resource:9090
  authHost: http://192.168.99.100:8080

server:
  port: 7070

spring:
  application:
    name: zuul

zuul:
  routes:
    qwerty:
      path: /profile/**
      url: ${nas.resourceHost}
#    uaa:
#      path: /uaa/**
#      url: http://localhost:8080
#      stripPrefix: false

security:
  oauth2:
    resource:
      token-info-uri: http://none.no
      jwt:
        key-value: 123
    client:
      client-id: zuul
      client-secret: zuul123
      access-token-uri: ${nas.authHost}/auth/oauth/token
      user-authorization-uri: ${nas.authHost}/auth/oauth/authorize

logging:
  level:
    org.springframework.security: DEBUG