server:
  port: 7070
  context-path: /zuul

spring:
  application:
    name: zuul

zuul:
  routes:
    qwerty:
      path: /qwerty/**
      url: http://localhost:9090

security:
  oauth2:
    resource:
      token-info-uri: http://ya.ru
      jwt:
        key-value: 123
    client:
      client-id: zuul
      client-secret: zuul123
      access-token-uri: http://localhost:8080/uaa/oauth/token
      user-authorization-uri: http://localhost:8080/uaa/oauth/authorize

logging:
  level:
    org.springframework.security: DEBUG