nas:
  resourceHost: http://resource:9090
  authHost: http://192.168.99.100:8080/auth

server:
  port: 7070

spring:
  application:
    name: zuul

zuul:
  routes:
    qwerty:
      path: /profile/**
      url: ${nas.resourceHost}
      sensitiveHeaders: Cookie,Set-Cookie
#    uaa:
#      path: /uaa/**
#      url: http://localhost:8080
#      stripPrefix: false

security:
  oauth2:
    resource:
      token-info-uri: http://none.no
      jwt:
        key-value: 123
    client:
      client-id: zuul
      client-secret: zuul123
      access-token-uri: ${nas.authHost}/oauth/token
      user-authorization-uri: ${nas.authHost}/oauth/authorize
      use-current-uri: false
      pre-established-redirect-uri: http://192.168.99.100:7070/login
logging:
  level:
    org.springframework.security: DEBUG

proxy:
  auth:
    routes:
      qwerty: passthru
