resources:
- name: HelloDockerGradle
  type: git
  source:
    uri: https://github.com/eshepelyuk/CodeForBlog.git
    branch: master

jobs:
  - name: HellDockerGradle
    plan:
      - get: HelloDockerGradle 
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: frekele/java, tag: jdk8}
          inputs:
            - name: src
          run:
            path: ls
            args: ["-la"]
