resources:
  - name: CodeForBlog
    type: git
    source:
      uri: https://github.com/eshepelyuk/CodeForBlog.git
      branch: master

jobs:
  - name: HellDockerGradle
    plan:
      - get: CodeForBlog 
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: frekele/java, tag: jdk8}
          run:
            path: ls
            args: ["-la"]
