version: '2'
services:
  
  mongo:
    image: "mongo:3"
  
  elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
  
  graylog:
    image: graylog2/server:2.1.2-1
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://192.168.99.100:9000/api
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201/udp:12201/udp"
      - "1514/udp:1514/udp"
    volumes:
      - "/usr/share/graylog/data"
  
  graylog-test-docker:
    image: eshepelyuk/graylog-test
    logging:
      driver: gelf
      options:
        gelf-address: udp://graylog.app:12201

  graylog-test-logback:
    image: eshepelyuk/graylog-test
    environment:
      GRAYLOG_HOST: graylog.app
      GRAYLOG_SOURCE: eshepelyuk
